---
## Numpy
- data가 많을수록 빨라진다. 

In [1]:
import numpy as np

In [2]:
data1 = [6,7.5,8,0,1]

In [3]:
# numpy를 이용하여 1차원 배열로 변형하기
# 다 실수로 바뀜
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인하기
arr1.shape

(5,)

---
### 2차원

In [5]:
data2 = [
    [1,2,3,4],
    [5,6,7,8]
]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape

(2, 4)

In [8]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# 0으로 구성된 3페이지의 5행 2열의 3차원 배열 생성
# 맨 처음 값이 page , 그 다음 행 , 그 다음 열
np.zeros([3,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [10]:
# 1로만 구성된 배열 생성
np.ones([3,5,2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [13]:
# 10으로 구성된 배열 생성
np.full(5,10)
np.full([5,2],10)
np.full([3,5,2],10)

array([[[10, 10],
        [10, 10],
        [10, 10],
        [10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10],
        [10, 10],
        [10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10],
        [10, 10],
        [10, 10],
        [10, 10]]])

In [ ]:
# 0으로 구성된 3행 5열 배열 생성
np.zeros((3,5))

In [ ]:
# 8로 구성된 3행 5열 배열 생성
np.full((3,5),8)

In [ ]:
# 범위가 있는 배열
np.arange(10,15)

In [ ]:
# 정수형으로 이루어진 배열 -> 실수형으로 변환
arr = np.array([1,2,3,4,5],dtype=np.int64)
arr.dtype

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

---
### 행렬 연산

In [ ]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
arr2 = np.array([
    [7,8,9],
    [10,11,12]
])

In [ ]:
arr1 + arr2

In [ ]:
arr1 - arr2

In [ ]:
arr1 * arr2

In [ ]:
arr1 * 2

In [ ]:
np.sqrt(arr1)

In [ ]:
1 / arr1 # 역수

In [23]:
arr = np.arange(1,11,dtype=np.float64)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
arr[5]

6.0

In [25]:
arr[5:9]

array([6., 7., 8., 9.])

In [16]:
# 손상된 이미지 복원시킬 때 요렇게 사용한다. 
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [26]:
arr[:5]

array([1., 2., 3., 4., 5.])

In [ ]:
arr[8:]

In [30]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

In [ ]:
# 2번 행의 자료 출력
arr2d[2,]

In [ ]:
# 1에서 2번행의 자료 출력
arr2d[1:3,]

In [ ]:
# 3번 열의 자료 출력
arr2d[:,3]

In [ ]:
# 0,1 열의 자료 출력
arr2d[:,0:2]

In [ ]:
# 1행 2열의 자료 출력
arr2d[1,2]

In [ ]:
# 이거 한게 차원 축소 한 것이다. -> 미분과 같은 개념
# 이러한 것을 언제 쓰냐??
# 과대적합 -> train data가 test data에 너무 맞혀져 있다.
# 과소적합 -> train data가 test data에 너무 맞혀져 있지 않다.
arr2d[:2,1:3] = 0
arr2d

---
### 난수 발생
- rand : 0 ~ 1 사이의 균일 분포 <br><br>
- randn : 가우시안 표준 정규 분포 <br><br>
- randint : 균일분포의 정수 난수 <br><br>

207

In [52]:
names = np.array([
    'charles',
    'kenny',
    'hayoung',
    'charles',
    'hayoung',
    'kenny',
    'kenny'
])

In [51]:
data = np.random.randn(7,4)
data

array([[ 0.06192303,  0.03092917,  0.73936457, -0.40581358],
       [-1.36456183,  1.08738817,  0.52279981,  0.06399889],
       [-0.18346674,  1.52407808,  1.66291041, -2.15267908],
       [-0.67243751,  0.2741836 , -1.70347937,  0.13659716],
       [ 1.31230274,  1.2029972 ,  0.30983227,  0.87720558],
       [-1.60668308,  2.03093357, -0.39299518, -0.53515702],
       [-0.52004617,  1.23146774,  0.32915206, -0.39014513]])

In [55]:
# Mask
names == 'Charles'
data[names == 'charles',] # True에 해당되는 행 출력

array([[ 0.06192303,  0.03092917,  0.73936457, -0.40581358],
       [-0.67243751,  0.2741836 , -1.70347937,  0.13659716]])

In [74]:
arr = np.arange(1,10).reshape(3,3)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
data[(names == 'charles') | (names == 'kenny'),:]

In [ ]:
data[data[:,3] < 0 ,:] = 0
data

In [ ]:
# 정렬
arr = np.random.randn(8)
arr

In [ ]:
# 오름 차순 정렬
np.sort(arr)

In [ ]:
# 내림 차순 정렬
np.sort(arr)[::-1]

In [75]:
arr = np.random.rand(5,3)
arr

array([[0.13689288, 0.28856275, 0.79549419],
       [0.43980038, 0.10857901, 0.40444895],
       [0.41691819, 0.76794499, 0.87006521],
       [0.37243807, 0.13943116, 0.24783815],
       [0.88444862, 0.47291702, 0.78282391]])

In [77]:
# 열방향 오름차순
np.sort(arr,axis=0)

# 열방향 내름차순
np.sort(arr,axis=0)[::-1]

array([[0.88444862, 0.76794499, 0.87006521],
       [0.43980038, 0.47291702, 0.79549419],
       [0.41691819, 0.28856275, 0.78282391],
       [0.37243807, 0.13943116, 0.40444895],
       [0.13689288, 0.10857901, 0.24783815]])

In [78]:
# 행방향 오름차순
np.sort(arr,axis=1)
# 행방향 내림차순
np.sort(arr,axis=1)[:,::-1]

SyntaxError: invalid syntax (1100719795.py, line 4)

---
### reshape
- 차원을 변환하는 것

In [31]:
# 1차원 데이터 생성
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
# 2차원 배열로 reshape
arr1 = np.reshape(arr,(2,2,-1))
arr1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# 3차원 배열로 reshape
arr2 = np.reshape(arr1, (2,2,2)) #(page, row , column)
arr2

In [ ]:
# 2차원 배열을 1차원으로
# 딥러닝 할 때는 1이 있어야 된다.
# -1의 의미가 맨끝을 의미하므로 개수를 모를 떄 사용할 수 있다. 
arr3 = np.reshape(arr1, (-1,1))
arr3

In [50]:
arr4 = arr1.reshape(-1)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr3 == arr4

In [ ]:
# 3차원 배열을 1차원으로 변경
arr5=arr2.reshape(-1,1)

In [ ]:
arr5 == arr4